import { Person } from "src/person/entities/person.entity";


export const personsDB: Partial<Person>[] = [
    {
        first_name: 'Luis',
        last_name: 'Gonzalez',
        dni: '12345678',
        email: 'luis@luis',
        phone: "23456789",
        address: 'Calle 123',
        location: 'CABA',
        nationality: 'Argentino',
        birthdate: new Date(),
    },
    {
        first_name: 'Jorge',
        last_name: 'Gonzalez',
        dni: '1345678',
        email: 'jorge@jorge',
        phone: "123456789",
        address: 'Calle 123',
        location: 'CABA',
        nationality: 'Argentino',
        birthdate: new Date(),
    },
    {
        first_name: 'Carlos',
        last_name: 'Gonzalez',
        dni: '12345618',
        email: 'carlos@carlos',
        phone: "123456789",
        address: 'Calle 123',
        location: 'CABA',
        nationality: 'Argentino',
        birthdate: new Date(),
    },
    {
        first_name: 'Lucas',
        last_name: 'Gonzalez',
        dni: '12345628',
        email: 'lucas@lucas',
        phone: "123456789",
        address: 'Calle 123',
        location: 'CABA',
        nationality: 'Argentino',
        birthdate: new Date(),
    },
    {
        first_name: 'Sandra',
        last_name: 'Gonzalez',
        dni: '12345638',
        email: 'sandra@sandra',
        phone: "123456789",
        address: 'Calle 123',
        location: 'CABA',
        nationality: 'Argentino',
        birthdate: new Date(),
    }
]