import { MigrationInterface, QueryRunner } from "typeorm";

export class Delclinicalhistory1719584574044 implements MigrationInterface {
    name = 'Delclinicalhistory1719584574044'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "stock"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "stock" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "price" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productsReport" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "productsReport" ADD "quantity" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_serv" DROP CONSTRAINT "UQ_6ddd112993478d00054a1b30bbd"`);
        await queryRunner.query(`ALTER TABLE "dental_serv" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ADD CONSTRAINT "UQ_6ddd112993478d00054a1b30bbd" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ALTER COLUMN "price" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "dental_serv" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ADD "description" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auths" DROP CONSTRAINT "UQ_a28e912dc6bde5945582f2be0a2"`);
        await queryRunner.query(`ALTER TABLE "auths" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "auths" ADD "email" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auths" ADD CONSTRAINT "UQ_a28e912dc6bde5945582f2be0a2" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "auths" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "auths" ADD "password" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "first_name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "last_name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "birthdate"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "birthdate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "UQ_c18da65793895769252e363e34d"`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "dni"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "dni" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "UQ_c18da65793895769252e363e34d" UNIQUE ("dni")`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "UQ_c77e8752faa45901af2b245dff2"`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "email" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "UQ_c77e8752faa45901af2b245dff2" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "nationality"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "nationality" character varying`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "deleteDate"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "deleteDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "dentists" DROP COLUMN "career"`);
        await queryRunner.query(`ALTER TABLE "dentists" ADD "career" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dentists" DROP COLUMN "speciality"`);
        await queryRunner.query(`ALTER TABLE "dentists" ADD "speciality" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "date_time"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "date_time" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "description" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP CONSTRAINT "PK_a142ab57a241b44ba9e1f4feab4"`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP CONSTRAINT "UQ_a142ab57a241b44ba9e1f4feab4"`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "slug_name"`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "slug_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD CONSTRAINT "PK_a142ab57a241b44ba9e1f4feab4" PRIMARY KEY ("slug_name")`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD CONSTRAINT "UQ_a142ab57a241b44ba9e1f4feab4" UNIQUE ("slug_name")`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "title" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "value" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "first_name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "last_name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "UQ_0ba53efff3e03d98b0dd52a7f6d"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "dni"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "dni" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "UQ_0ba53efff3e03d98b0dd52a7f6d" UNIQUE ("dni")`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "birthdate"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "birthdate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "UQ_85d472bf0e9dd55ce9a8268c3e0"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "email" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "UQ_85d472bf0e9dd55ce9a8268c3e0" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "reason" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deseases" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "deseases" ADD "name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_record" DROP COLUMN "health_Insurance"`);
        await queryRunner.query(`ALTER TABLE "dental_record" ADD "health_Insurance" character varying(25) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_record" DROP COLUMN "observations"`);
        await queryRunner.query(`ALTER TABLE "dental_record" ADD "observations" character varying(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_record" DROP COLUMN "medication"`);
        await queryRunner.query(`ALTER TABLE "dental_record" ADD "medication" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "productsReport" ADD CONSTRAINT "FK_1f24374b4390a040725b337dd23" FOREIGN KEY ("report_id") REFERENCES "report"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "FK_ef1d7960ba3545bf6103284c1a8" FOREIGN KEY ("auth") REFERENCES "auths"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dentists" ADD CONSTRAINT "FK_8aa1576056cbbb4db27683d3fd2" FOREIGN KEY ("person_id") REFERENCES "people"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_b829cf7046dfb9d4e510984e977" FOREIGN KEY ("person_id") REFERENCES "people"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_10e1c3f1dd3fc996189f55f1be5" FOREIGN KEY ("dentis_id") REFERENCES "dentists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_f77953c373efb8ab146d98e90c3" FOREIGN KEY ("serviceId") REFERENCES "dental_serv"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_624dba53e23dc24c94313775a31" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deseases" ADD CONSTRAINT "FK_f2254c5ab0e8e90f8d0c99f84cd" FOREIGN KEY ("recordId") REFERENCES "dental_record"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products_report" ADD CONSTRAINT "FK_7d32d4e5167ef6c6f84e78ce35c" FOREIGN KEY ("productReport_id") REFERENCES "productsReport"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_report" ADD CONSTRAINT "FK_0e5fef8c43e7c2ab4ab21336a52" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "people_roles" ADD CONSTRAINT "FK_6a98be3db49637ef3d8130e755f" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "people_roles" ADD CONSTRAINT "FK_51935f695d98071cbac73668e4d" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "people_roles" DROP CONSTRAINT "FK_51935f695d98071cbac73668e4d"`);
        await queryRunner.query(`ALTER TABLE "people_roles" DROP CONSTRAINT "FK_6a98be3db49637ef3d8130e755f"`);
        await queryRunner.query(`ALTER TABLE "products_report" DROP CONSTRAINT "FK_0e5fef8c43e7c2ab4ab21336a52"`);
        await queryRunner.query(`ALTER TABLE "products_report" DROP CONSTRAINT "FK_7d32d4e5167ef6c6f84e78ce35c"`);
        await queryRunner.query(`ALTER TABLE "deseases" DROP CONSTRAINT "FK_f2254c5ab0e8e90f8d0c99f84cd"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_624dba53e23dc24c94313775a31"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_f77953c373efb8ab146d98e90c3"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_13c2e57cb81b44f062ba24df57d"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_10e1c3f1dd3fc996189f55f1be5"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_b829cf7046dfb9d4e510984e977"`);
        await queryRunner.query(`ALTER TABLE "dentists" DROP CONSTRAINT "FK_8aa1576056cbbb4db27683d3fd2"`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "FK_ef1d7960ba3545bf6103284c1a8"`);
        await queryRunner.query(`ALTER TABLE "productsReport" DROP CONSTRAINT "FK_1f24374b4390a040725b337dd23"`);
        await queryRunner.query(`ALTER TABLE "dental_record" DROP COLUMN "medication"`);
        await queryRunner.query(`ALTER TABLE "dental_record" ADD "medication" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_record" DROP COLUMN "observations"`);
        await queryRunner.query(`ALTER TABLE "dental_record" ADD "observations" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_record" DROP COLUMN "health_Insurance"`);
        await queryRunner.query(`ALTER TABLE "dental_record" ADD "health_Insurance" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deseases" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "deseases" ADD "name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "reason"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "reason" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "UQ_85d472bf0e9dd55ce9a8268c3e0"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "email" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "UQ_85d472bf0e9dd55ce9a8268c3e0" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "birthdate"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "birthdate" 'timestamp without time zone' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "address" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "UQ_0ba53efff3e03d98b0dd52a7f6d"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "dni"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "dni" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "UQ_0ba53efff3e03d98b0dd52a7f6d" UNIQUE ("dni")`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "last_name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guests" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "guests" ADD "first_name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "value" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "title"`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "title" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP CONSTRAINT "UQ_a142ab57a241b44ba9e1f4feab4"`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP CONSTRAINT "PK_a142ab57a241b44ba9e1f4feab4"`);
        await queryRunner.query(`ALTER TABLE "system_configs" DROP COLUMN "slug_name"`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD "slug_name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD CONSTRAINT "UQ_a142ab57a241b44ba9e1f4feab4" UNIQUE ("slug_name")`);
        await queryRunner.query(`ALTER TABLE "system_configs" ADD CONSTRAINT "PK_a142ab57a241b44ba9e1f4feab4" PRIMARY KEY ("slug_name")`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "description" 'character varying'`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP COLUMN "date_time"`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD "date_time" 'timestamp without time zone' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dentists" DROP COLUMN "speciality"`);
        await queryRunner.query(`ALTER TABLE "dentists" ADD "speciality" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dentists" DROP COLUMN "career"`);
        await queryRunner.query(`ALTER TABLE "dentists" ADD "career" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "deleteDate"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "deleteDate" 'timestamp without time zone'`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "nationality"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "nationality" 'character varying'`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "location" 'character varying'`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "address" 'character varying'`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "UQ_c77e8752faa45901af2b245dff2"`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "email" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "UQ_c77e8752faa45901af2b245dff2" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "phone" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "UQ_c18da65793895769252e363e34d"`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "dni"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "dni" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "UQ_c18da65793895769252e363e34d" UNIQUE ("dni")`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "birthdate"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "birthdate" 'timestamp without time zone' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "last_name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "people" ADD "first_name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "description" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "auths" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "auths" ADD "password" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auths" DROP CONSTRAINT "UQ_a28e912dc6bde5945582f2be0a2"`);
        await queryRunner.query(`ALTER TABLE "auths" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "auths" ADD "email" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auths" ADD CONSTRAINT "UQ_a28e912dc6bde5945582f2be0a2" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "dental_serv" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ADD "description" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ALTER COLUMN "price" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "dental_serv" DROP CONSTRAINT "UQ_6ddd112993478d00054a1b30bbd"`);
        await queryRunner.query(`ALTER TABLE "dental_serv" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ADD "name" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dental_serv" ADD CONSTRAINT "UQ_6ddd112993478d00054a1b30bbd" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "productsReport" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "productsReport" ADD "quantity" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "description" 'character varying' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "price" 'double precision' NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "stock"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "stock" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "name" 'character varying' NOT NULL`);
    }

}
